### ISSUE TITLE
Feature request: Flag to enable RAG

### ISSUE THREAD

**Issue by cooktheryan** [opendatahub-io/llama-stack-k8s-operator-legacy#18]
The operator should have the ability to optionally deploy Milvus-lite as the vectorDB. This can be accomplished by adding the following to the llama stack run config

```
  vector_io:
  - provider_id: milvus
    provider_type: inline::milvus
    config:
     db_path: ${env.MILVUS_DB_PATH}
```

The DB path we could either make an optional path or hardcode something that we can attach a pvc to

**Comment by zanetworker** [comment]
The question here is how much should we have a 1:1 map between API and config given confiug is pretty much in-flux.

**Comment by rhuss** [comment]
If I understand correctly, up to now, we don't create an own run config but pick up what is included in the distribution image. We can of course change that and e.g. allow an override of the run config, either entirely or on a per-provider basis (and add this e.g. to the `LlamaStackDistribution` CRD schema like with a 

```yaml
...
spec:
  runtime:
    mode: merge | overwrite
    providers:
      vectorIo: 
      - id: milvus
        type: inline:milvus
        config: 
          dbPath: ...
```

that then during deployment will be used to create the proper runtime configuration as needed by the LLS server.

(Whether to translate, e.g., `db_path` to the more K8s-like camel case version `dbPath:` remains to be discussed. Same for `vectorIo` vs. `vector_io`)
