### ISSUE TITLE
Bug: no such key: image evaluating rule: Only one of name or image can be specified

### ISSUE THREAD

**Issue by patilsuraj767** [opendatahub-io/llama-stack-k8s-operator-legacy#32]
When trying to apply the below CR 
```
  replicas: 1
  server:
    distribution:
      name: "ollama"
    containerSpec:
    .....
    .....
```
I got the error 
```
The LlamaStackDistribution "llamastackdistribution-sample" is invalid: spec.server.distribution: Invalid value: "object": no such key: image evaluating rule: Only one of name or image can be specified
```
